-- AlterTable
ALTER TABLE `settings` ADD COLUMN `color` VARCHAR(191) NOT NULL DEFAULT '#c6c6c6',
    ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updated_at` DATETIME(3) NULL;
